clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    - vault
    - golang-external-secrets
  subscriptions: {}
  projects:
    - default
  applications:
    vault:
      name: vault
      namespace: vault
      project: default
      path: common/hashicorp-vault
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: default
      path: common/golang-external-secrets
  imperative: {}
  managedClusterGroups: {}
